// @ts-check

import { sveltekit } from "@sveltejs/kit/vite"
import linku from "./src/linku.json"

export const words = Object.fromEntries(
  Object.entries(linku.data).map(([key, word]) => [
    key,
    {
      book:
        word.book == "pu"
          ? "pu"
          : word.book == "ku suli"
          ? "ku suli"
          : word.book == "ku lili"
          ? "ku lili"
          : "nimi sin",
      definition: word.def.en,
      sitelenPona: "sitelen_pona" in word ? word.sitelen_pona : word,
      sitelenSitelen:
        "sitelen_sitelen" in word ? word.sitelen_sitelen : undefined,
      word: word.word,
      usage: word.usage_category,
      short: {
        Pingo: "car",
        a: "(emphasis, emotion or confirmation)",
        aka: "cross-like shape, intersection, overlap",
        akesi: "reptile, amphibian",
        ako: "(general interjection)",
        ala: "not, no, nothing, 0",
        alasa: "hunt, forage, seek, attempt, try to",
        ale: "all, every, 100",
        alente:
          "the set of every possible human concept subtracted from the set of concepts already covered by established toki pona words weighted by their relative usage",
        ali: "all, countless, every, everything, 100",
        alu: "(la reversed)",
        anpa: "bow, humble, low, dependent, bottom",
        ante: "different, alter, change, other",
        anu: "(between options, X or Y), choose",
        apeja: "guilt, shame, disgrace, embarass",
        awase: "bump into, make contact with",
        awen: "endure, protect, safe, wait, continue",
        e: "(before direct object)",
        eki: "cross-like shape, intersection, overlap",
        en: "(between multiple subjects)",
        enko: "space, place, distance, size",
        epiku: "epic, cool, amazing",
        esun: "marker, shop, fair, bazaar, transaction",
        ete: "beyond, exceeding, outside of, more than",
        ewe: "stone, gravel, rock, pebble, lava, magma",
        i: "he, she, it, they",
        ijo: "thing, object, matter",
        ike: "bad, irrelevant, complex",
        iki: "he, she, it, they",
        ilo: "tool, machine",
        insa: "center, content, inside",
        ipi: "he, she, it, they",
        isipin: "think, brainstorm, rationalize, conclude, ponder",
        itomi: "indirect insult or disrespect, shade",
        jaki: "disgusting, sickly, toxic, unclean",
        jaku: "100",
        jalan: "foot",
        jami: "yummy, eliciting a positive sensory experience",
        jan: "human being, person, somebody",
        jans: "a particular group of early members of the ma pona Discord server",
        jasima: "reflect, mirror, be on opposite end of",
        je: "(indicates excitement)",
        jelo: "yellow, yellowish",
        jo: "have, carry, contain, hold",
        jonke: "goose, goose noise",
        ju: "(reserved for future use by Sonja Lang)",
        jule: "indeterminate, unpredictable, volatile, vibrate, shake",
        jume: "dream, fantasy",
        kala: "fish, marine animal, sea creature",
        kalama: "to produce a sound, recite, utter aloud",
        kalamARR: "pirate noise",
        kalijopilale:
          "Caryophyllales, cactus, carnation, beet, carnivorous plant",
        kama: "arrive, come, become, manage to, succeed",
        kamalawala: "anarchy, uprising, revolt, rebellion",
        kan: "with, among, in the company of",
        kapa: "extrusion, protrusion, hill, mountain, button",
        kapesi: "brown, gray",
        kasi: "plant, vegetation, herb, leaf",
        ke: "(acknowledgement or acceptance)",
        ken: "be able/allowed to, can, may, possible",
        kepeken: "to use, with, using, by means of",
        kepen: "[shortened kepeken]",
        kese: "queer, LGBT+",
        ki: "(relative clause marker)",
        kijetesantakalu: "Musteloidea, racoon, coati, weasel",
        kiki: "spiky, sharp, angle, point, triangular",
        kili: "fruit, vegetable",
        kin: "too, also, as well",
        kipisi: "split, cut, slice",
        kisa: "cat",
        kiwen: "hard object, metal, rock, stone",
        ko: "clay, dough, semi-solid, paste, powder",
        kokosila: "speak non-TP when toki pona is more appropriate",
        kon: "air, breath, essence, spirit",
        konsi: "to notify, to let know",
        konwe: "animate, life, autonomy, organism, alive",
        kosan: "guard, protect, defend, shield",
        ku: "the toki pona dictionary by Sonja Lang",
        kule: "colorful, pigmented, painted",
        kulijo: "(appreciation, acknowledgement, cool, fine, okay)",
        kulu: "[shortened kulupu], 6",
        kulupu: "community, group, society, tribe",
        kuntu: "laughter, chuckle, laugh, comedy, humor",
        kute: "ear, hear, listen, obey",
        kutopoma: 'the Korean group chat "kulupu pi toki pona pi ma Anku"',
        la: "(between context phrase and main sentence)",
        lanpan: "take, seize, catch, receive, get",
        lape: "sleep, rest",
        laso: "blue, green",
        lawa: "head, control, guide, lead, plan, rule",
        leko: "stairs, corner, cube",
        len: "cloth, fabric, privacy",
        lete: "cold, cool, uncooked, raw",
        li: "(before the verb)",
        lijokuku: "to agree (with laughter)",
        likujo: "collection, assortment, arrangement, 7",
        lili: "little, small, few",
        linja: "cord, hair, rope, thread, yard, line",
        linluwi: "network, internet, connection, weave, braid",
        lipu: "book, document, paper, record, website",
        lo: "(before prepositional phrase)",
        loje: "red, reddish",
        loka: "limb",
        lokon: "(a compromise between lukin and oko)",
        lon: "present, real, true, exist, located at",
        lu: "(reserved for future use by Sonja Lang)",
        luka: "arm, hand, tactile organ, interact, 5",
        lukin: "look, examine, read, watch, try to, eye",
        lupa: "door, hole, orfice, window",
        ma: "earth, land, world, country, soil",
        majuna: "old, aged, ancient",
        mama: "parent, creator, caretaker",
        mani: "money, cash, livestock",
        meli: "woman, female, wife",
        melome: "sapphic, lesbian, wlw",
        meso: "midpoint, medium, mediocre",
        mi: "I, me, we, us",
        mije: "man, male, husband",
        mijomi: "gay, mlm",
        misa: "Glires or Eulipotyphla; rat, mouse, squirrel, rabbit, rodent",
        misikeke: "medicine, medical",
        moku: "eat, drink, consume, food",
        moli: "dead, dying",
        molusa: "squishy animal, snail, slug, sponge",
        monsi: "back, behind, rear",
        monsuta: "fear, monster, danger",
        mu: "(animal noise)",
        mulapisu: "pizza",
        mun: "moon, star, night sky object",
        musi: "artistic, entertaining, playful",
        mute: "many, a lot, much, very, 20",
        n: "(thinking, pondering, humming)",
        nalanja: "orange (color)",
        namako: "embellishment, spice, extra",
        nanpa: "-th (ordinal), number",
        nasa: "unusual, strange, silly",
        nasin: "way, method, path, road",
        natu: "relationship, correlation, cross, intersection, to overlap",
        neja: "4",
        nele: "lack of privacy, clear, transparent, unobstructed",
        nena: "bump, button, hill, nose",
        ni: "this, that",
        nimi: "name, word",
        nimisin: "non-pu word, new word, joke word",
        nja: "(meow, feline sound)",
        noka: "foot, leg",
        nu: "(reserved for future use by Sonja Lang)",
        o: "(vocative or imperative)",
        ojuta: '"ligma"',
        oke: "(acknowledgement or acceptance)",
        okepuma: "boomer, Baby Boomer, inconsiderate elder",
        oki: "(acknowledgement or acceptance)",
        oko: "eye, ocular, visual",
        olin: "love, respect, show affection to",
        omekalike: "(proper name) a song by jan Usawi",
        omekapo: "goodbye, farewell, eat a good fish",
        omen: "sarcasm, irony",
        ona: "he, she, it, they",
        oni: "dream, mystical state, vision, entrance",
        open: "begin, start, open, turn on",
        owe: "Orwellian, totalitarian",
        pa: "(bruh, disbelief, exasperation)",
        pakala: "break, damage, harm",
        pake: "stop, interrupt, prevent",
        pali: "do, work on, build, make",
        palisa: "branch, rod, stick",
        pan: "bread, corn, grain, oat, rice, wheat",
        pana: "give, send, emit, put",
        pasila: "good, easy, simple, relaxed, peaceful",
        pata: "brother, sister, sibling",
        peta: "green, alive, ecofriendly",
        peto: "cry, tears, sad",
        pi: "of",
        pika: "electric, mechanical, online, lightning",
        pilin: "heart, feeling, emotion",
        pimeja: "black, dark, unlit",
        pini: "complete, end, finish",
        pipi: "bug, insect, spider",
        pipo: "annoy, bothersome, boring",
        po: "4",
        poka: "hip, side, nearby, beside",
        poki: "container, bag, bowl, cup, drawer",
        polinpin: "bowling pin",
        pomotolo: "effective, useful",
        pona: "good, friendly, peaceful, simple",
        poni: "pony",
        powe: "unreal, false, pretend, deceive",
        pu: "(interacting with) the official TP book",
        puwa: "fluffy, soft, squishy",
        sama: "same, similar, sibling, peer, like",
        samu: "wanting to create new words",
        san: "3",
        seli: "fire, heat source, cook",
        selo: "outer layer, bark, peel, skin, boundary",
        seme: "what? which?",
        sewi: "above, high, elevated, divine, sacred",
        sijelo: "body, physical state, torso",
        sike: "round, ball, circle, cycle, of one year",
        sikomo: "enlightened, epic",
        sin: "new, fresh, additional, another, extra",
        sina: "you",
        sinpin: "face, foremost, front, wall",
        sipi: "ego, self, own",
        sitelen: "image, symbol, write",
        slape: "[humorous synonym of lape]",
        soko: "fungus, fungi",
        sona: "know, know how to",
        soto: "left, left side",
        soweli: "animal, beast, land mammal",
        su: "(reserved for future use by Sonja Lang)",
        suke: "[typo of sike]",
        suli: "big, large, important, adult",
        suno: "sun, light, glow, shine",
        supa: "horizontal surface, table",
        sutopatikuna: "platypus",
        suwi: "sweet, fragrant, cute, innocent",
        taki: "sticky, magnetic, bond",
        tan: "by, from, because of",
        taso: "but, however, only",
        tawa: "go to, toward, for, to, POV",
        te: "(open quote)",
        teje: "right, right side",
        telo: "water, liquid, beverage",
        ten: "[shortened tenpo]",
        tenpo: "time, duration",
        to: "(close quote)",
        tokana: "focus, attention, concentrate",
        toki: "communicate, say, speak, talk",
        toma: "[typo of tomo]",
        tomo: "indoor space, building, house, room",
        tonsi: "non-binary",
        tu: "2",
        tuli: "3",
        u: "(reserved for future use by Sonja Lang)",
        umesu:
          "amaze people by being on top of the leaderboard of a toki pona game",
        unpa: "have sexual relations",
        unu: "purple",
        usawi: "magic, sorcery, enchant",
        uta: "mouth, lips, jaw",
        utala: "battle, challenge, struggle against",
        wa: "(awe or amazement)",
        waleja: "context, topic, pertain to, relevant",
        walo: "white, whitish, pale",
        wan: "unique, united, 1",
        waso: "bird, flying creature",
        wasoweli: "animal that's both waso & soweli",
        wawa: "strong, energetic",
        wawajete: "something that appears to break the rules but doesnt'",
        we: "(transition from one sentence to another)",
        weka: "absent, away, ignored",
        wekama: "leave and come back",
        wi: "we (excluding you)",
        wile: "must, need, want",
        wuwojiti: "to break TP phonotactics",
        yupekosi: "to revise a creative work and worsen it",
        yutu: "the star emoji used for the starboard (#pona-kulupu in ma pona)",
      }[/** @type {keyof typeof linku.data} */ (key)],
    },
  ])
)

/** @type {import("vite").UserConfig} */
const config = {
  plugins: [
    sveltekit(),
    {
      name: "vite-plugin-linku",
      resolveId(id) {
        if (id === "virtual:linku") {
          return "\0virtual:linku"
        }
      },
      load(id) {
        if (id === "\0virtual:linku") {
          return `export const words = ` + JSON.stringify(words)
        }
      },
    },
  ],
}

export default config
